<?php
/**
 * Copyright 2017 WompMobile, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>

<!doctype html>
<?php
    $product = $block->getProduct();
?>
<html ⚡>
<head>
    <meta charset="utf-8">

    <script async src="https://cdn.ampproject.org/v0.js"></script>

    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-image-lightbox" src="https://cdn.ampproject.org/v0/amp-image-lightbox-0.1.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-element="amp-social-share" src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.1.js"></script>

    <!-- Make your page discoverable: https://www.ampproject.org/docs/guides/discovery -->
    <link rel="canonical" href="<?php echo $block->getProductCanonicalUrl() ?>">

    <!-- Add custom fonts: https://www.ampproject.org/docs/guides/responsive/custom_fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

    <!-- Supported CSS: https://www.ampproject.org/docs/guides/responsive/style_pages -->
    <style amp-custom>
    body {
        font-family: "Roboto", sans-serif;
    }

    .header {
        background-color: #0696b7;
        position: relative;
        box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.2), 0 1px 5px 0 rgba(0,0,0,0.12);
        padding-top: 52px;
    }

    .header #sample-menu {
        position: absolute;
        top: 0;
        left: 0;
        font-size: 18px;
        font-weight: 700;
        color: white;
        padding: 13px;
    }

    .header #sample-logo {
        position: absolute;
        top: 0;
        left: 36px;
        font-size: 20px;
        font-weight: 400;
        color: white;
        margin: 0 16px;
        height: 32px;
        text-decoration: none;
        line-height: 52px;
        white-space: nowrap;
    }

    #drawermenu {
        color: black;
        padding-left: 16px;
        padding-right: 16px;
    }

    #drawermenu h2 {
        margin-top: 24px;
        font-size: 20px;
    }

    #drawermenu ul.categories {
        padding-left: 0;
        list-style-type: none;
    }

    #drawermenu ul.categories ul {
        margin-top: 1ex;
        padding-left: 1em;
    }

    #drawermenu ul a {
        text-decoration: none;
        color: darkblue;
    }

    #drawermenu .drawermenu-button {
        z-index: 2;
        position: fixed;
        right: 6px;
        top: 6px;
        font-size: 24px;
        line-height: 24px;
        background-color: transparent;
        border: 0;
    }

    .contents {
        padding: 0 10px;
        display: flex;
        flex-direction: column;
    }

    .product-title {
        margin-top: 20px;
        margin-bottom: 8px;
    }

    .product-field {
        margin-top: 8px;
        margin-bottom: 8px;
    }

    .product-description {
    }

    .product-gallery {
        margin-top: 12px;
        margin-bottom: 12px;
    }

    .close-gallery-button {
        z-index: 1;
        position: absolute;
        right: 6px;
        top: 6px;
        font-size: 24px;
        line-height: 24px;
        background-color: black;
        color: white;
        border: 1px solid gray;
    }

    amp-image-lightbox img {
        object-fit: contain;
        background: rgba(0,0,0,0.9);
    }

    .product-price {
        font-weight: 600;
        font-size: 18px;
    }

    #add-to-cart label {
        display: inline-block;
        margin: 0;
    }

    #add-to-cart .quantity {
        font-size: 16px;
        text-align: right;
        height: 24px;
        width: 2em;
        display: inline-block;
        margin-left: 6px;
        padding-right: 4px;
    }

    #add-to-cart .button {
        font-size: 16px;
        background-color: #0696b7;
        color: white;
        border: 1px solid black;
        padding: 6px 12px;
        text-align: center;
        display: inline-block;
        margin-left: 6px;
    }

    .hide {
        display: none;
    }

    .show {
        display: block;
    }

    .product-social {
        margin-top: 12px;
        margin-bottom: 12px;
    }

    .copyright-branding {
        flex: 1;
        width: 100vw;
        margin-top: 8px;
        margin-bottom: 8px;
    }

    .copyright-branding p {
        color: gray;
        font-size: 80%;
        margin: 0;
    }

    .copyright-branding a {
        text-decoration: none;
        color: #0696b7;
    }
    </style>

    <!-- AMP SEO -->
    <script type="application/ld+json">
    {
        "@context": "http://schema.org/",
        "@type": "Product",
        "name": <?php echo json_encode($product->getName()) ?>,
        "image": "<?php echo $block->getProductImageUrl() ?>",
        "description": <?php echo json_encode(strip_tags($product->getShortDescription())) ?>
    }
    </script>

    <!-- AMP Boilerplate Code: https://www.ampproject.org/docs/reference/spec/amp-boilerplate -->
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    </head>
    <body>

        <!-- Categories -->
        <amp-sidebar id="drawermenu" layout="nodisplay">
            <h2>Categories</h2>
            <?php echo $block->generateCategoriesHTML() ?>
            <button class="drawermenu-button"
                    on="tap:drawermenu.toggle"
                    role="button"
                    tabindex="0">×</button>
        </amp-sidebar>

        <!-- Drawer icon -->
        <div class="header">
            <a id="sample-menu" on="tap:drawermenu.toggle">
                <amp-img srcset="<?php
                        echo $block->getViewFileUrl('WompMobile_AmpProductExample::img/ic_menu_white_1x_web_24dp.png')
                    ?> 1x, <?php
                        echo $block->getViewFileUrl('WompMobile_AmpProductExample::img/ic_menu_white_2x_web_24dp.png')
                    ?> 2x" width="24" height="24" alt="navigation">
                </amp-img>
            </a>
            <a id="sample-logo" href="#">
                WompMobile &hearts; AMP
            </a>
        </div>

        <div class="contents">

            <!-- Product title -->
            <h2 class="product-title">
                <?php echo $block->escapeHtml($product->getName()) ?>
            </h2>

            <!-- Product tagline -->
            <p class="product-tagline product-field">
                <?php echo $block->escapeHtml(strip_tags($product->getShortDescription())) ?>
            </p>

            <!-- Product image gallery -->
            <amp-carousel id="product-gallery"
                height="320"
                layout="fixed-height"
                type="slides"
                class="show"><?php foreach($block->getProductGalleryInfo() as $imageInfo): ?>
                        <amp-img src="<?php echo $imageInfo['url'] ?>"
                                 width="<?php echo strval($imageInfo['width']) ?>"
                                 height="<?php echo strval($imageInfo['height']) ?>"
                                 layout="responsive"
                                 on="tap:gallery-lightbox"
                                 role="button"
                                 tabindex="0"
                                 alt="Product Image">
                        </amp-img>
                    <?php endforeach; ?>
            </amp-carousel>

            <!-- Zoom image -->
            <amp-image-lightbox id="gallery-lightbox" layout="nodisplay">
                <div on="tap:gallery-lightbox.close" role="button" tabindex="0">
                    <button class="close-gallery-button"
                            on="tap:gallery-lightbox.close"
                            role="button"
                            tabindex="0">×</button>
                </div>
            </amp-image-lightbox>

            <!-- Product description -->
            <p class="product-description product-field">
                <?php echo $block->escapeHtml(strip_tags($product->getDescription())) ?>
            </p>

            <!-- Product price -->
            <p class="product-price product-field">
                $<?php echo $block->getProductPrice() ?>
            </p>

            <!-- Add to cart action -->
            <form class="product-field" id="add-to-cart" method="GET" action="/checkout/cart/add/" target="_top">
                <!-- Quantity -->
                <label for="quantity">Quantity:</label>
                <!-- TODO: Get max quantity -->
                <input class="quantity" type="number" name="qty" min="1" value="1">

                <!-- Add to cart button -->
                <input type="submit" class="button" value="Add to Cart">

                <!-- Hidden fields -->
                <input type="hidden" name="product" value="<?php echo $block->escapeHtml($block->getProductId()) ?>">
                <input type="hidden" name="form_key" value="<?php echo $block->escapeHtml($block->getFormKey()) ?>">
                <div submit-error>
                    <template type="amp-mustache">
                        Error! Looks like something went wrong with your shopping cart, please try to add an item again. {{error}}
                    </template>
                </div>
            </form>

            <!-- Social links -->
            <div class="product-social">
                <amp-social-share type="twitter"
                                  width="30"
                                  height="22"></amp-social-share>
                <amp-social-share type="facebook"
                                  width="30"
                                  height="22"
                                  data-attribution="254325784911610"></amp-social-share>
                <amp-social-share type="gplus"
                                  width="30"
                                  height="22"></amp-social-share>
                <amp-social-share type="email"
                                  width="30"
                                  height="22"></amp-social-share>
                <amp-social-share type="pinterest"
                                  width="33"
                                  height="22"></amp-social-share>
            </div>

            <!-- Copyright/Branding -->
            <div class="copyright-branding">
                <p>
                    Copyright 2017 <a href="http://www.wompmobile.com/">WompMobile, Inc.</a><br>
                    <a href="https://ampbyexample.com/samples_templates/product_page/">AMP Product Page Sample</a> used as reference.
                </p>
            </div>

        </div>

    </body>
</html>
