<!doctype html>
<?php
    $product = $block->getProduct();
?>
<html amp>
<head>
    <meta charset="utf-8">
    <meta name="amp-experiment-token" content="HfmyLgNLmblRg3Alqy164Vywr">
    <script async src="https://cdn.ampproject.org/v0.js"></script>

    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
    <script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
    <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.1.js"></script>
    <script async custom-element="amp-social-share" src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js"></script>
    <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
    <script async custom-element="amp-image-lightbox" src="https://cdn.ampproject.org/v0/amp-image-lightbox-0.1.js"></script>
    <script async custom-element="amp-youtube" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>

    <!-- TODO --> <link rel="canonical" href="https://ampbyexample.com/samples_templates/product_page/">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-custom>

    article#preview {
      background-color: #f5f5f5;
    }
    amp-carousel {
      margin: 0;
    }

    .header {
      position: relative;
      box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);
      padding-top: 52px;
    }
    .header {
      background-color: #607D8B;
    }
    .header #sample-menu {
      position:absolute;
      top:0;
      left: 0;
      font-size: 18px;
      font-weight: 700;
      color: white;
      text-transform: uppercase;
      padding: 13px;
    }
    .header #sample-logo {
      position:absolute;
      top:0;
      left:36px;
      font-size: 18px;
      font-weight: 400;
      color: white;
      text-transform: uppercase;
      margin: 0 16px;
      height: 32px;
      text-decoration: none;
      line-height: 52px;
    }

    .header form {
      padding: 0;
    }
    .header input::-webkit-search-decoration,
    .header input::-webkit-search-cancel-button {
      display: none;
    }
    .header input[type=submit] {
      position:absolute;
      top:10px; right:8px;
      background-color: #eb407a;
      background-position: center;
      background-repeat: no-repeat;
      background-image: -webkit-image-set(
        url('/img/ic_search_white_1x_web_24dp.png') 1x,
        url('/img/ic_search_white_2x_web_24dp.png') 2x
      );
      border: 0 none;
      height: 32px;
      width: 36px;
      -webkit-appearance: none;
      border-radius: 0;
      -moz-border-top-right-radius: 4px;
      -moz-border-bottom-right-radius: 4px;
      -webkit-border-top-right-radius: 4px;
      -webkit-border-bottom-right-radius: 4px;
      border-top-right-radius: 4px;
      border-bottom-right-radius: 4px;
    }
    .header input[type=search] {
      position: absolute;
      top: 10px;
      right: 24px;
      background: #ededed ;
      padding: 0 8px;
      width: 20vw;
      height: 32px;
      font-family: inherit;
      font-size: 100%;
      -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      box-sizing: border-box;
      -webkit-appearance: none;
      border: solid 0px #ccc;
      border-radius: 0;
      -moz-border-top-left-radius: 4px;
      -moz-border-bottom-left-radius: 4px;
      -webkit-border-top-left-radius: 4px;
      -webkit-border-bottom-left-radius: 4px;
      border-top-left-radius: 4px;
      border-bottom-left-radius: 4px;
      -webkit-transition: all .9s;
      -moz-transition: all .9s;
      transition: all .9s ease;
    }
    .header input[type=search]:focus {
      box-sizing: border-box;
      width: 80vw;
      max-width: 700px;
      height: 32px;
      background-color: #fff;
      border-color: #eb407a;
      -webkit-box-shadow: 0 0 5px rgba(109,207,246,.5);
      -moz-box-shadow: 0 0 5px rgba(109,207,246,.5);
      box-shadow: 0 0 5px rgba(109,207,246,.5);
      outline:none;
    }
    .header input:-moz-placeholder,
    .header input::-webkit-input-placeholder {
      color: #999;
    }
    .header input:focus + #sample-logo {
      visibility: hidden;
      opacity: 0;
      transition: visibility 0s 0.7s, opacity 0.7s ease;
    }
    .header input + #sample-logo {
      visibility: visible;
      opacity: 1;
      transition: opacity 1.5s ease;
    }
    @media (min-width: 600px) {
      .header input[type=search] {
        width: 100px;
      }
      .header input[type=search]:focus {
        width: 600px;
      }
    }

    .items,
    amp-list.items > div {
      display: flex;
      justify-content:space-around;
      flex-wrap: wrap;
    }
    .item {
      flex-grow: 1;
      flex-shrink: 1;
    }

    .tile {
      background-color: white;
      width: 120px;
      height: 200px;
      display: block;
      margin: 8px;
      -webkit-tap-highlight-color: #eee;
      max-width: 200px;
    }
    @media (max-width: 500px) {
      .items .tile {
        width: 150px;
        height: 200px;
      }
    }
    .tile:active {
      background-color: #eee;
    }
    .tile p {
      margin: 0;
      padding: 0 8px;
      font-size: 14px;
      line-height:20px;
    }
    .tile .name {
      margin-top: 8px;
    }
    .tile .price {
      margin-bottom: 8px;
    }
    .tile .price,
    .tile .star {
      color: black;
    }
    #product-description {
      clear: both;
    }
    amp-lightbox {
      background: rgba(0,0,0,0.8);
      width: 100%;
      height: 100%;
      position: absolute;
    }
    amp-accordion h4 {
      font-size: 18px;
    }
    amp-carousel .selected {
      border: solid 2px red;
    }
    .amp-youtube-container {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;
    }
    .video {
      flex: 1;
    }
    .price-description {
      color: grey;
      font-weight: 400;
      margin-top: 24px;
      margin-bottom: 16px;
      padding: 0 16px;
    }
    .product-gallery > ul {
      margin: 0;
      padding: 0;
      float: left;
      list-style: none;
      line-height: 0;
    }
    .product-gallery > ul > li {
      cursor: pointer;
      margin: 0 1em 1em 1em;
      opacity: 1;
      will-change: opacity;
      transition: all 0.3s cubic-bezier(.25,.8,.25,1);
    }
    .product-gallery > ul > li:active {
      opacity: 0.5;
    }
    .product-gallery > ul > li:focus {
      outline: none;
    }
    form#order label {
      display: inline;
      font-weight: 500;
      font-size: 16px;
      margin: 0;
    }
    form#order .button {
      width: 100%;
      max-width: 400px;
      align-self: center;
      margin: 16px 20%;
      box-sizing: border-box;
    }
    form#order.amp-form-submitting [name=add-to-cart] {
      color: #666;
      background-color: #aaa;
      cursor: default;
    }
    form#order amp-selector > ul {
      list-style: none;
      display: flex;
      align-items: flex-end;
      justify-content: end;
    }
    form#order amp-selector > ul li {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-ri?ght: 8px;
      background: white;
      height: 40px;
      min-width: 40px;
      width: auto;
    }
    form#order amp-selector [option] {
      outline: none;
    }
    form#order amp-selector amp-img[option][selected] {
      outline-width: 1px;
      outline-style: solid;
      outline-color: #eb407a;
      background: none;
    }
    form#order amp-selector:not([disabled]) [option][selected]:not([disabled]), amp-img.selected {
      will-change: box-shadow;
      box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
      transition: box-shadow 0.3s cubic-bezier(.25,.8,.25,1);
      color: #fff;
    }

    form#order amp-selector:not([disabled]) [option][selected]:not([disabled]):not(.unavailable):not(.square) {
      background-color: #eb407a;
    }

    form#order amp-selector:not([disabled]) [option][selected]:not([disabled]):not(.unavailable).square {
      outline: 1px solid #eb407a;
    }

    form#order amp-selector:not([disabled]) [option]:not([selected]):not([disabled]), amp-img:not([.selected]) {
      will-change: box-shadow;
      box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
      transition: box-shadow 0.3s cubic-bezier(.25,.8,.25,1);
    }

    form#order amp-selector[name=color] div:not([selected]):not([disabled]) {
      opacity: 0.6;
    }
    .hide {
      display: none;
    }
    .show {
      display: block;
    }
    .unavailable {
      position: relative;
      background: gray;
      overflow: hidden;
      opacity: 0.6;
      pointer-events: none;
      user-select: none;
    }

    .unavailable:before, .unavailable:after {
      position: absolute;
      content: '';
      background: grey;
      display: block;
      width: auto;
      height: 1px;
      min-width: 56px;
      -webkit-transform: rotate(-45deg);
      transform: rotate(-45deg);
      left: -11px;
      right: 0;
      top: 0;
      bottom: 0;
      margin: auto;
      border-bottom: 2px solid;
    }

    .unavailable:after {
        -webkit-transform: rotate(45deg);
        transform: rotate(45deg);
    }

    div.square {
      width: 40px;
      height: 40px;
    }

    .green {
      background-color: #008000;
    }

    .red {
      background-color: #FF0000;
    }

    .golden {
      background-color: #DAA520;
    }

    @media (max-width: 1024px) {
      .product-gallery > ul {
        display: none;
      }
    }
    .info-button {
      background: -webkit-image-set(
        url(/img/ic_info_outline_black_24dp_1x.png) 1x,
        url(/img/ic_info_outline_black_24dp_2x.png) 2x
      );
      background-repeat: no-repeat;
      width: 24px;
      height: 24px;
      margin-top: 4px;
    }

    .info {
      margin: 0 auto;
      background: #fff;
    }

    .lightbox {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
    }

    .ampTabContainer {
        display: flex;
        flex-wrap: wrap;
    }

    .tabButton {
        list-style: none;
        text-align: center;
        cursor: pointer;
        outline: none;
    }

    amp-selector [option][selected] {
      outline: #fff;
    }

    .tabContent {
        line-height: 1.5rem;
        display: none;
        width: 100%;
        order: 1;
    }

    .tabButton[selected]::after {
      content: '';
      display: block;
      height: 4px;
      background: linear-gradient(90deg,#94103e 0,#db004d);
    }

    .tabButton[selected]+.tabContent {
        display: block;
    }

    .items, amp-list.items > div {
      justify-content: flex-start;
    }
    .close-gallery-button {
      z-index: 1;
      position: absolute;
      right: 0;
    }
    </style>



    <!-- AMP SEO -->
    <script type="application/ld+json">
    {
        "@context": "http://schema.org/",
        "@type": "Product",
        "name": <?php echo json_encode($product->getName()) ?>,
        "image": "<?php echo $block->getBaseImageUrl($product) ?>",
        "description": <?php echo json_encode(strip_tags($product->getShortDescription())) ?>
        /* TODO: Based on reviews
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "4.4",
            "reviewCount": "88"
        },
        */
    }
    </script>

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    </head>
    <body>



      <!-- TODO: Generate from category tree -->
      <amp-sidebar id="drawermenu" layout="nodisplay">
        <a href="/" class="caps text-decoration-none block p1">Products</a>
        <hr/>
        <a class="caps text-decoration-none block p1" href="/samples_templates/product_browse_page/preview/">Fruit</a>
        <a class="caps text-decoration-none block p1" href="/samples_templates/product_browse_page/preview/">Vegetable</a>
        <a class="caps text-decoration-none block p1" href="/samples_templates/product_browse_page/preview/">More</a>
      </amp-sidebar>



      <div class="header">
        <a id="sample-menu" on="tap:drawermenu.toggle">
          <amp-img srcset="<?php echo $block->getViewFileUrl('AlanKent_AmpExample::img/ic_menu_white_1x_web_24dp.png') ?> 1x, <?php echo $block->getViewFileUrl('AlanKent_AmpExample::img/ic_menu_white_2x_web_24dp.png') ?> 2x"
                  width="24" height="24"
                  alt="navigation"></amp-img>
        </a>
        <!-- TODO: Search
        <form method="GET" action="/samples_templates/product_browse_page/source/search" target="_top">
          <input name="search" type="search" placeholder="Search">
          <a id="sample-logo" href="/">Product</a>
          <input type="submit" value="">
        </form>
        -->
      </div>

      <!-- TODO: Product title? -->
      <h2 class="m1"><?php echo $block->escapeHtml($product->getName()) ?></h2>



      <div class="m1">
        <amp-social-share type="twitter"
                          width="30"
                          height="22"></amp-social-share>
        <amp-social-share type="facebook"
                          width="30"
                          height="22"
                          data-attribution="254325784911610"></amp-social-share>
        <amp-social-share type="gplus"
                          width="30"
                          height="22"></amp-social-share>
        <amp-social-share type="email"
                          width="30"
                          height="22"></amp-social-share>
        <amp-social-share type="pinterest"
                          width="33"
                          height="22"></amp-social-share>
      </div>

      <!-- Product description -->
      <p id="product-description" class="m1"><?php echo $product->getDescription() ?></p>




      <!-- TODO: product video?
      <button class="ampstart-btn caps m1 mb3" on="tap:watch-video-lightbox" >
        Show Video
      </button>

      <amp-lightbox id="watch-video-lightbox" layout="nodisplay">
        <div class="amp-youtube-container">
          <div class="video">
            <a on="tap:watch-video-lightbox.close" role="button" tabindex="0">
              Close
            </a>
            <amp-youtube width="480" height="270"
                                     layout="responsive"
                                     data-videoid="lBTCB7yLs8Y">
            </amp-youtube>
          </div>
        </div>
      </amp-lightbox>
      -->


  <!-- Product image gallery -->
  <div class="product-gallery">

    <amp-carousel id="product-image-carousel"
            width="1024" height="682"
            layout="responsive"
            type="slides"
            [slide]="product.selectedSlide"
            on="slideChange: AMP.setState({product: {selectedSlide: event.index}})"
            class="show">
      <?php foreach($block->getGalleryInfo() as $imageInfo) {
        echo '<amp-img src="' . $imageInfo['url'] . '"' .
                'width="' . strval($imageInfo['width']) . '"' .
                'height="' . strval($imageInfo['height']) . '"' .
                'layout="responsive" on="tap:gallery-lightbox"
                role="button" tabindex="0"></amp-img>';
      }?>
    </amp-carousel>

    <!-- Displays zoomed version of image. -->
    <amp-image-lightbox id="gallery-lightbox" layout="nodisplay">
      <div on="tap:gallery-lightbox.close" role="button"
          tabindex="0">
          <button class="ampstart-btn caps m2 close-gallery-button" on="tap:gallery-lightbox.close"
            role="button" tabindex="0">
            Close
          </button>
      </div>
    </amp-image-lightbox>

  </div>


  <amp-state id="product">
    <script type="application/json">
    {
      "relatedProductsSrc": "/json/related_products.json",
      "selectedColor": "green",
      "selectedSize": "S",
      "selectedSlide": 0,
      "green": {
        "sizes": {
          "S": "$5.99",
          "M": "$5.99",
          "L": "unavailable"
        },
        "defaultSize": "S"
      },
      "golden": {
        "sizes": {
          "S": "$9.99",
          "M": "unavailable",
          "L": "$9.99"
        },
        "defaultSize": "L"
      },
      "red": {
        "sizes": {
          "S": "$7.99",
          "M": "$7.99",
          "L": "$7.99"
        },
        "defaultSize": "M"
      }
    }
    </script>
  </amp-state>



      <p class="price-description">Price:
        <span [text]="product[product.selectedColor].sizes[product.selectedSize]">$1.99</span>
    </p>






      <form id="order" method="POST"
            action-xhr="/samples_templates/product_page/add_to_cart"
            target="_top" class="flex flex-wrap m1">
        <div class="items-center flex">
          <label for="color">Color:</label>
          <amp-selector name="color"
                  layout="container"
                  [selected]="product.selectedColor"
                  on="select:AMP.setState({
                    product: {
                      selectedColor: event.targetOption,
                      selectedSlide: 0,
                      selectedSize: product[event.targetOption].sizes[product.selectedSize] != 'unavailable' ? product.selectedSize : product[event.targetOption].defaultSize
                    }
                  })">
            <ul class="p0 m1">
              <li>
                <div option="green" selected class="square green" width="40" height="40"></div>
              </li>
              <li>
                <div option="golden" class="square golden" width="40" height="40"></div>
              </li>
              <li>
                <div option="red" class="square red" width="40" height="40"></div>
              </li>
            </ul>
          </amp-selector>
        </div>

        <!-- Quantity -->
        <div class="items-center flex">
          <label for="quantity">Quantity:</label>
          <amp-selector name="quantity" layout="container">
            <ul class="p0 m1">
              <li option="1" selected>1</li>
              <li option="2">2</li>
              <li option="3">3</li>
            </ul>
          </amp-selector>
        </div>

        <!-- TODO: Get sizes -->
        <div class="items-center flex">
          <label for="size">Size:</label>
          <amp-selector name="size" layout="container"
                  on="select:AMP.setState({ product: {selectedSize: event.targetOption}})"
                  [selected]="(product[product.selectedColor].sizes[product.selectedSize] != 'unavailable')
                      ? product.selectedSize
                      : product[product.selectedColor].defaultSize">
            <ul class="p0 m1">
              <li option="S" class=""
                  [class]="(product[product.selectedColor].sizes['S'] != 'unavailable')
                      ? ''
                      : 'unavailable'">S</li>
              <li option="M" class="" selected
                  [class]="(product[product.selectedColor].sizes['M'] != 'unavailable')
                      ? ''
                      : 'unavailable'">M</li>
              <li option="L" class="unavailable"
                  [class]="(product[product.selectedColor].sizes['L'] != 'unavailable')
                      ? ''
                      : 'unavailable'">L</li>
            </ul>
          </amp-selector>
        </div>

        <!-- Add to cart button -->
        <div class="items-center flex my1">
          <input type="submit" class="ampstart-btn caps" name="add-to-cart" value="add to cart">
        </div>

        <!-- TODO: Hidden fields? -->
        <input type="hidden" name="name" value="Apple">
        <input type="hidden" name="price" value="$1.99">
        <input name="clientId" type="hidden" value="CLIENT_ID(cart)" data-amp-replace="CLIENT_ID">
        <div submit-error>
          <template type="amp-mustache">
            Error! Looks like something went wrong with your shopping cart, please try to add an item again. {{error}}
          </template>
        </div>
      </form>



  <!-- TODO: tabs for ABOUT/SPECS/SIZE, different content. -->
  <amp-selector role="tablist"
  layout="container"
  class="ampTabContainer ampstart-headerbar-nav">
  <div role="tab"
    class="tabButton h4 ampstart-nav-item"
    selected
    option="a">ABOUT</div>
  <div role="tabpanel"
      class="tabContent p1 p">Fruit is rich in vitamins and minerals. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
  <div role="tab"
    class="tabButton h4 ampstart-nav-item"
    option="b">SPECS</div>
  <div role="tabpanel"
    class="tabContent p1 p">Always wash fruit before eating. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
  <div role="tab"
      class="tabButton h4 ampstart-nav-item"
      option="c">SIZE</div>
  <div role="tabpanel"
      class="tabContent p1 p">Size may vary. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>
</amp-selector>



    <div class="items-center flex">
      <h2 id="related-products" class="m1 inline-block">Related products
      <amp-lightbox id="my-lightbox" layout="nodisplay">
        <div class="lightbox" on="tap:my-lightbox.close" role="button"
            tabindex="0">
          <div class="info">
            <h4 class="p2">Products that have been bought together</h4>
            <button class="ampstart-btn caps mx2 mb2" on="tap:my-lightbox.close"
              role="button" tabindex="0">
              Close
            </button>
        </div>
        </div>
      </amp-lightbox>
    </h2>
      <button class="info-button border-none mr1" on="tap:my-lightbox" role="button" tabindex="0">
      </button>
    </div>

    <amp-list class="items m1"
              width="auto"
              height="100"
              layout="fixed-height"
              src="/json/related_products.json"
              [src]="product.relatedProductsSrc">
      <template type="amp-mustache">
        <a class="text-decoration-none p1" href="/samples_templates/product_page/preview/">
          <amp-img width="640"
                   height="426"
                   layout="responsive"
                   alt="{{name}}"
                   src="{{img}}"></amp-img>
                 <p class="name">{{name}}</p>
                 <p class="star">{{{stars}}}</p>
                 <p class="price">${{price}}</p>
        </a>
      </template>
    </amp-list>
  ?
    <button class="ampstart-btn caps m1 mb3" id="listSrcButton" on="tap:AMP.setState({product: {relatedProductsSrc: '/json/more_related_products.json'}})">Show more</button>


<!--
  <amp-analytics type="googleanalytics">
    <script type="application/json">
        {
          "vars": {
              "account": "UA-73836974-1"
          },
          "triggers": {
              "default pageview": {
                  "on": "visible",
                  "request": "pageview",
                  "vars": {
                      "title": "Product"
                  }
              }
          }
      }
    </script>
  </amp-analytics>
-->
    </body>
</html>
